### ISSUE TITLE
For  05-pseudo-whitening, IndexError: list index out of range

### ISSUE THREAD

**Issue by jiapei100** [jbornschein/mpi4py-examples#14]
```console
pi@pi01:~/Downloads/mpi4py-examples $ mpirun --np 16 --hostfile ~/hostfile  05-pseudo-whitening
Traceback (most recent call last):
  File "/home/pi/Downloads/mpi4py-examples/05-pseudo-whitening", line 26, in <module>
    in_fname = sys.argv[-2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/Downloads/mpi4py-examples/05-pseudo-whitening", line 26, in <module>
    in_fname = sys.argv[-2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/Downloads/mpi4py-examples/05-pseudo-whitening", line 26, in <module>
    in_fname = sys.argv[-2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/Downloads/mpi4py-examples/05-pseudo-whitening", line 26, in <module>
    in_fname = sys.argv[-2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/Downloads/mpi4py-examples/05-pseudo-whitening", line 26, in <module>
    in_fname = sys.argv[-2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/Downloads/mpi4py-examples/05-pseudo-whitening", line 26, in <module>
    in_fname = sys.argv[-2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/Downloads/mpi4py-examples/05-pseudo-whitening", line 26, in <module>
    in_fname = sys.argv[-2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/Downloads/mpi4py-examples/05-pseudo-whitening", line 26, in <module>
    in_fname = sys.argv[-2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/Downloads/mpi4py-examples/05-pseudo-whitening", line 26, in <module>
    in_fname = sys.argv[-2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/Downloads/mpi4py-examples/05-pseudo-whitening", line 26, in <module>
    in_fname = sys.argv[-2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/Downloads/mpi4py-examples/05-pseudo-whitening", line 26, in <module>
    in_fname = sys.argv[-2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/Downloads/mpi4py-examples/05-pseudo-whitening", line 26, in <module>
    in_fname = sys.argv[-2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/Downloads/mpi4py-examples/05-pseudo-whitening", line 26, in <module>
    in_fname = sys.argv[-2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/Downloads/mpi4py-examples/05-pseudo-whitening", line 26, in <module>
    in_fname = sys.argv[-2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/Downloads/mpi4py-examples/05-pseudo-whitening", line 26, in <module>
    in_fname = sys.argv[-2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/pi/Downloads/mpi4py-examples/05-pseudo-whitening", line 26, in <module>
    in_fname = sys.argv[-2]
IndexError: list index out of range
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[1099,1],7]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by jbornschein** [comment]
This example requires you to specify an input *.h5 file, as shortly described in the file-header.

I do admit that this is a bit silly, because almost nobody will have .h5 files with images available.

But given that this repository contains examples that are somewhat more intended for reading than for actually running & doing something useful I'm just gonna close this. 

A reasonable way forward would be to replace this example with some other computation that can be done trivially parallel.
